obstacle_range: 1.0
raytrace_range: 2.0
robot_radius: 0.15
footprint_padding: 0.01

robot_base_frame: base_link
update_frequency: 10.0
publish_frequency: 8.0
transform_tolerance: 0.5

resolution: 0.1


#layer definitions
static:
    enable: true
    map_topic: /map
    subscribe_to_updates: true

obstacles_laser:
    enabled: true
    observation_sources: laser
    laser: {data_type: LaserScan, clearing: true, marking: true, topic: /scan, inf_is_valid: true}

inflation:
    enabled: true
    inflation_radius: 0.08

